@{

RootModule = 'Posh-ACME.Deploy.psm1'
ModuleVersion = '2.0.0'
GUID = '79819e0a-30db-4742-bcc4-0c956273db51'
Author = 'Ryan Bolger'
Copyright = '(c) 2018 Ryan Bolger. All rights reserved.'
Description = 'Deployment helper functions for Posh-ACME'
CompatiblePSEditions = 'Desktop'
PowerShellVersion = '5.1'
DotNetFrameworkVersion = '4.7.1'

FunctionsToExport = @(
    'Set-ExchangeCertificate'
    'Set-IISCertificate'
    'Set-IISCertificateOld'
    'Set-IISFTPCertificate'
    'Set-PBIRSCertificate'
    'Set-RASSTPCertificate'
    'Set-RDGWCertificate'
    'Set-RDSHCertificate'
    'Set-WinRMCertificate'
    'Set-NPSCertificate'
)
CmdletsToExport = @()
VariablesToExport = @()
AliasesToExport = @(
    'Set-IISCertificateNew'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'LetsEncrypt','ssl','tls','certificates','acme','powershell','posh-acme'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/rmbolger/Posh-ACME.Deploy/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/rmbolger/Posh-ACME.Deploy'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## 2.0.0 (2024-06-20)

### Enhancements

* `Set-IISCertificate` (formerly `Set-IISCertificateNew`) now supports additional SSL binding flags on newer versions of Windows including:
  * DisableHTTP2
  * DisableOCSPStapling
  * DisableQUIC
  * DisableTLS13
  * DisableLegacyTLS
* Documentation Revamp
  * https://docs.dvolve.net/Posh-ACME.Deploy/ is a new dedicated website for module documentation. The site is currently generated using the Markdown files in the `docs` folder in the main project repository by [MkDocs](https://www.mkdocs.org/). So it should now be easier to contribute fixes and updates.
  * The native module help is now also generated by [platyPS](https://github.com/PowerShell/platyPS) from the Markdown files in `docs/Functions`.
  * `Get-Help <function name> -Online` should now open your browser to the appropriate page on the documentation site.

### Breaking Changes

* `Set-IISCertificateNew` (which relies on the `IISAdministration` module) has been renamed to `Set-IISCertificate`. An alias for `Set-IISCertificateNew` is still included so scripts referencing it should not break. But users are encouraged to update their scripts to the non-alias name.
* `Set-IISCertificate` (which relies on the legacy `WebAdministration` module) has been deprecated and renamed to `Set-IISCertificateOld`. The new `Set-IISCertificate` includes a superset of the old parameters. So scripts don't necessarily need to change. However, the new function is dependent on having version 1.1.0.0 or later of the `IISAdministration` module installed. It is recommended to install the necessary module and validate the new function works. Alternatively, scripts can also be updated to use the old function while it remains in the module.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
